[package]
name = "dearrow-browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
bitflags = "2.3.3"
csv = "1.2.2"
serde = { version = "1.0.173", features = ["derive", "rc"] }
