[package]
name = "dearrow-browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
anyhow = "1.0.72"
base64 = "0.21.2"
bitflags = "2.3.3"
chrono = "0.4.26"
csv = "1.2.2"
getrandom = "0.2.10"
serde = { version = "1.0.173", features = ["derive", "rc"] }
toml = "0.7.6"
