[workspace]
members = ["dearrow-browser-server", "dearrow-browser-api", "dearrow-parser", "dearrow-browser-frontend"]

[workspace.dependencies]
serde = { version = "1.0.173", features = ["derive", "rc"] }
anyhow = "1.0.72"
