[package]
name = "dearrow-parser"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
bitflags = "2.3.3"
csv = "1.2.2"
serde.workspace = true
