[package]
name = "dearrow-browser-frontend"
version.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
chrono = { version = "0.4.26", default-features = false, features = ["wasmbind", "alloc", "clock"] }
dearrow-browser-api = { path = "../dearrow-browser-api" }
reqwest = { version = "0.11.18", features = ["json"] }
strum = { version = "0.25.0", features = ["derive"] }
serde.workspace = true
web-sys = { version = "0.3.64", features = ["KeyboardEvent", "HtmlInputElement", "Window", "Document", "Element", "Location"] }
# yew = { version = "0.20.0", features = ["csr"] }
# yew-router = "0.17.0"
yew = { git = "https://github.com/yewstack/yew.git", rev = "7ef8e0da18808e9e4ef3e7ff36a1d6a20019d087", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" , rev = "7ef8e0da18808e9e4ef3e7ff36a1d6a20019d087" }
yew-hooks = { git = "https://github.com/mini-bomba/yew-hooks.git", rev = "034de0118daeaafca2fa1efb2dab726af70ce4a6" }
gloo-console = "0.2.3"
