[package]
name = "dearrow-browser-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
web-sys = { version = "0.3.64", features = ["KeyboardEvent", "HtmlInputElement", "Window", "Document", "Element"] }
yew = { version = "0.20.0", features = ["csr"] }
