[package]
name = "dearrow-browser-api"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dearrow-parser = { path = "../dearrow-parser", optional = true }
serde.workspace = true
